export default [
    {
        index: 0,
        key: '1',
        price: '$6872',
        title: 'messages',
        model: '2022',
        people:'sogand',
        time:'1y ago',
        description:'Text messaging, or texting, is the act of composing and sending electronic messages, typically consisting of alphabetic and numeric characters, between two or more users of mobile devices, desktops/laptops, or another type of compatible computer. Text messages may be sent over a cellular network, or may also be sent via an Internet connection .',
        picture: require("../../assets/b2.png"),
        age:+4,
    },
    {
        index: 1,
        key: '2',
        price: '$7960',
        title: 'Text messages',
        model: '2021',
        people:'negar',
        time:'2y ago',
        description:'Text messaging, or texting, is the act of composing and sending electronic messages, typically consisting of alphabetic and numeric characters, between two or more users of mobile devices, desktops/laptops, or another type of compatible computer. Text messages may be sent over a cellular network, or may also be sent via an Internet connection',
        picture: require("../../assets/b2.png"),
        age:+5,

    },
    {
        index: 2,
        key: '3',
        price: '$9446',
        title: 'Text messages',
        model: '2020',
        people:'salva',
        time:'3y ago',
        description:'Text messaging, or texting, is the act of composing and sending electronic messages, typically consisting of alphabetic and numeric characters, between two or more users of mobile devices, desktops/laptops, or another type of compatible computer. Text messages may be sent over a cellular network, or may also be sent via an Internet connection',
        picture: require("../../assets/b2.png"),
        age:+8,
    },
    {
        index: 3,
        key: '4',
        price: '$5968',
        title: 'Dia 018',
        model: '2022',
        people:'sara',
        time:'8y ago',
        description:'Text messaging, or texting, is the act of composing and sending electronic messages, typically consisting of alphabetic and numeric characters, between two or more users of mobile devices, desktops/laptops, or another type of compatible computer. Text messages may be sent over a cellular network, or may also be sent via an Internet connection',
        picture: require("../../assets/b2.png"),
        age:+3,
    },
]
